### ISSUE TITLE
Lacks of data file to train K-Means clustering

### ISSUE THREAD

**Issue by ducalpha** [abhijith-athreya/ASDUS#1]
K-Means clustering algorithm in `Lab_Web_Service_KMeans.ipynb` requires a model to do the prediction. The model is created in `perform_clustering(path='./try.csv', n_clusters=2, sep='|'):` function which uses features in the training file `./try.csv` but I cannot find any such file nor any way to generate it from the provided data.

How to generate such feature data for training the k-means clustering model? If the data is available, could it be uploaded?

**Comment by abhijith-athreya** [comment]
The try.csv is just a placeholder fot the filename which contains the features for the domain-independent model. This feature file gets generated from the Java Code: DomainIndependentModel.java
