### ISSUE TITLE
Errors when running `DomainIndependentModel`

### ISSUE THREAD

**Issue by ducalpha** [abhijith-athreya/ASDUS#2]
1. Run `Lab_Web_Service_KMeans.ipynb`, the server successfully started.
2. Run class `com.lab.model.DomainIndependentModel`, expected result: title/prose-segmented output file is generated.

`public static void performClustering()` prints `0` and the following errors are generated.

```
Exception Encountered during Predict
Server returned HTTP response code: 500 for URL: http://localhost:12007/predict/5%7C1
```

The server (in the python notebook) prints errors:
```
...
Traceback (most recent call last):
  File "/Users/a/miniconda3/lib/python3.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/Users/a/miniconda3/lib/python3.7/site-packages/bottle.py", line 1742, in wrapper
    rv = callback(*a, **ka)
  File "<ipython-input-8-c0e00c2e0481>", line 12, in predict
    prediction = predict_label(X1=X1, X2=X2)
  File "<ipython-input-5-2025219ee135>", line 6, in predict_label
    model = pickle.load(open('temp.pkl', 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: 'temp.pkl'
127.0.0.1 - - [31/Oct/2019 17:23:27] "GET /predict/123%7C39 HTTP/1.1" 500 758
```

**Comment by abhijith-athreya** [comment]
he perform_clustering method in Lab_Web_Service_KMeans.ipynb creates the kmeans model and dumps it in .pkl format. Please check if you have that file.

**Comment by ducalpha** [comment]
`Lab_Web_Service_KMeans.ipynb` calls `perform_clustering()` without any argument so `perform_clustering(path='./try.csv', n_clusters=2, sep='|')` looks for `try.csv`. However, as reported in issue #1, `DomainIndependentModel.java` does not generate any file called `try.csv`. Therefore, the program does not work at all.

**Comment by ruiyeNLP** [comment]
Hi I would say that ./try.csv is missing. Could you recall where this csv file is to make this project run?
