### ISSUE TITLE
How to generate data for `perform_clustering`?

### ISSUE THREAD

**Issue by ducalpha** [abhijith-athreya/ASDUS#3]
How to  generate data for `perform_clustering` method in `Lab_Web_Service_KMeans.ipynb`?

Lab_Web_Service_KMeans.ipynb calls `perform_clustering()` without any argument so `perform_clustering(path='./try.csv', n_clusters=2, sep='|')` looks for `try.csv`. However, as reported in issue #1 , `DomainIndependentModel.java` does not generate any file called `try.csv`.

**Comment by abhijith-athreya** [comment]
As I explained before, the feature  file for clustering is created by - DomainIndependentModel.java file. Please see the method- perform_top_down_parsing(...) this creates a csv file. This csv file will be used by the python code to perform clustering. You might want to rename the file saved by perform_top_down_parsing method to match the python's kmeans method.

**Comment by ducalpha** [comment]
Thank you for the instructions!

I got the KMeans model work by generating the `features.csv` from `DomainIndependentModel.java`'s `perform_top_down_parsing()` and rename the generated `features.csv` into `try.csv` for using with `perform_clustering` method in `Lab_Web_Service_KMeans.ipynb`.
