### ISSUE TITLE
Missing the file discourse.csv in the DomainIndependentModel

### ISSUE THREAD

**Issue by JFChi** [abhijith-athreya/ASDUS#4]
Hi, 

When I run the the java code of DomainIndependentModel, I find the repo does not provide me with the discourse.csv, could you please add it in the repo or provide me the link to download it. Thanks.

**Comment by abhijith-athreya** [comment]
Hi, 
The discourse.csv is not required. As the file which I was referring to is unavailable. You can comment the code and proceed.
